Shopmandus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('vendor.urls')),
     
]

app/urls.py
from unicodedata import name
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from sklearn import naive_bayes
from . import views
from app.views import AddToCartView, my_wishlist
from app.views import MyCartView
from app.views import ManageCartView
from app.views import EmptyCartView
from app.views import CheckoutView
from app.views import  CustomerRegistrationView
from app.views import  CustomerLogoutView
from app.views import  CustomerLoginView
from app.views import  CustomerProfileView
from app.views import   PasswordForgotView
from app.views import   PasswordResetView
from app.views import    SearchView 
from app.views import   KhaltiRequestView
from app.views import   KhaltiVerifyView 
from app.views import   CustomerOrderDetailView
from app.views import AdminLoginView  
from app.views import  AdminHomeView
from app.views import AdminOrderDetailView 
from app.views import  AdminOrderStatuChangeView    








urlpatterns = [
     path('', views.ProductView.as_view(), name="index"),
     path('product-detail/<int:pk>/', views.ProductDetailView.as_view(), name="product-detail"),
     path('search/', SearchView.as_view(), name="search"),
     path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
     path("my-cart/", MyCartView.as_view(), name="mycart"),
     path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
     path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
     path("checkout/", CheckoutView.as_view(), name="checkout"),
     path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),
     path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
     path("login/", CustomerLoginView.as_view(), name="customerlogin"),
     path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
     path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
     path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path('grow-your-business/', views.vendor, name='grow-your-business'),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path('success/',views.success,name="success"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),
    path('delete/<int:id>/', views.delete_data, name="deletedata"),
    path('<int:id>/', views.updatedata, name="updatedata"),
    path('my-wishlist',views.my_wishlist, name='my_wishlist'),
    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),
   path('add-wishlist',views.add_wishlist, name='add_wishlist'),
   path('deletewishlist/<int:id>/', views.delete_wishlist, name="deletewishlist"),
   



   


   
     




    



     
     




   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from statistics import mode
from tkinter import CASCADE
from turtle import ondrag
from venv import create
from django.db import models
from django.contrib.auth.models import User
from matplotlib.style import use

# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField(max_length=200)
   

    def __str__(self):
        return self.title

class Storage(models.Model):
    title = models.CharField(max_length=200)
   

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE,null=True, blank=True)
    storage = models.ForeignKey(Storage, on_delete=models.CASCADE,null=True, blank=True)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    full_description = models.TextField(null=True)
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)
    user = models.CharField(max_length=20, blank=True, null= True)
    Vendor_name = models.CharField(max_length=40,blank=True, null= True )
   
    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField(blank=True,null=True)

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
  
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)
    seller = models.CharField(max_length=100, null=True,blank=True)
   

    def __str__(self):
        return "Order: " + str(self.id)



class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
      
    

app/templates/app/Checkout.html
{% extends 'app/bases.html' %}
{% load static %}
{% block title %}Checkout{% endblock title %}

{% block main-contents %}
 
<div class="container">
    <div class="row my-3">
        <div class="col-md-6 my-3">
            
            <h3>Items in the cart</h3>
            <a href="{% url 'mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-sm-5">
            <br>
            <h3>Checkout Form</h3>
            <form action="" method="POST" class=" p-5">
                {% csrf_token %}
                {{form.as_p}}
             <button class="btn btn-info" >Place order</button></a> 
            </form>
            {% if messages %}
    <div class="col-lg-3 color03">
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
        </div>
    </div>
</div>

</div>
</div>


{% endblock main-contents %}

app/templates/app/Mycart.html
{% extends 'app/bases.html' %}
{% load static %}
{% block title %}MyCart{% endblock title %}

{% block main-contents %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br>
            <br>
            <h4>Items in my cart</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url "emptycart" %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'checkout'%}"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock main-contents %}

app/templates/app/Profile.html
{% extends 'app/bases.html' %}
{% load static %}

{% block title %}{{customer.full_name}}{% endblock title %}

{% block main-contents %}
<div class="container">
    <div class="row">
        <div class="col-md-4 my-5">
            
            <h3>Detail Information</h3><hr>
            <p><span class="font-weight-bold">Name: </span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address: </span> {{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span> {{customer.joined_on}}</p>
        </div>
        <div class="col-md-8 my-5">
            
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered on</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'customerorderdetail' ord.pk %}"> #ORDER_{{order.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


    {% endblock main-contents %}

app/templates/app/addtocart.html
{% extends 'app/bases.html' %}
{% load static %}
{% block title %}Add to Cart{% endblock title %}

{% block main-contents %}

<div class="container">
    <div class="row py-5 justify-content-center">
        <div class="col-md-5">
        <div class="alert alert-primary">
            The product was added successfully

        </div>
        </div>

    </div>
</div>




{% endblock main-contents %}

app/templates/app/customerregistration.html
{% extends 'app/bases.html' %}
{% load static %}
{% block title %}Customer Register{% endblock title %}

{% block main-contents %}

<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Customer Registration</h3><hr>
            <form action="" method="POST" class="shadow p-5">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Register</button>
            </form>
            {% comment %} <p> Already have an account? <a href="{% url 'customerlogin' %}">Login here</a></p> {% endcomment %}
            <br>
            <div class ="text-center text-primary fw-bold"><small> Existing User? <a href="{% url 'customerlogin' %}" class="text-danger">Login Now</a></small></div>
        </div>
    </div>
</div>


{% endblock main-contents %}

app/templates/app/index.html
{% extends 'app/bases.html' %}
{% load static %}
{% block title %}Online Shopping in Nepal| Best Deals, Price & Discount{% endblock title %}

{% block main-contents %}

	
	 <section class="slider-section pt-2 pb-2">
        <div class="container">
            <div class="slider-inner">
                <div class="row">

            
                    <div class="col-md-3">
                        <nav class="nav-category">
                            <h2>Categories</h2>
                                {%for p in category  %}
                            <ul class="menu-category">
                                <li><a href="/?category={{p.id}}">{{p.title }}</a></li>
                                {%endfor%}                               
                            </ul>                   
                        </nav>

                {% comment %} <nav class="nav-category my-2">
                            <h2>Brand</h2>
                                
                            <ul class="menu-category">
                                {% for i in brand %}
                                <li><a href="/?brand={{i.id}}">{{i.title}}</a></li>
                                {% endfor %}   
                            </ul>
                        </nav>   {% endcomment %}

                    </div>


                  
                    <div class="col-md-9">
                        <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner shadow-sm rounded">
                                <div class="carousel-item active">
                                    <img class="d-block w-100" src="{%static 'app//img/slides/slide1.jpg'%}" alt="First slide">
                                    <div class="carousel-caption d-none d-md-block">
                                      
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{%static 'app/img/slides/slide2.jpg'%}" alt="Second slide">
                                    <div class="carousel-caption d-none d-md-block">
                                       
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{%static 'app/img/slides/slide3.jpg'%}" alt="Third slide">
                                    <div class="carousel-caption d-none d-md-block">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End Slider -->
                    </div>
                </div>
            </div>
        </div>
    </section>

	<section class="pt-5 pb-5">
        <div class="container">
            <div class="row">


                <div class="col-md-4">
                    <div class="media">
                        <div class="iconbox iconmedium rounded-circle text-info mr-4">
                            <i class="fa fa-truck"></i>
                        </div>
                        <div class="media-body">
                            <h5>Fast Shipping</h5>
                           
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="media">
                        <div class="iconbox iconmedium rounded-circle text-purple mr-4">
                            <i class="fa fa-credit-card-alt"></i>
                        </div>
                        <div class="media-body">
                            <h5>Online Payment</h5>
                            
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="media">
                        <div class="iconbox iconmedium rounded-circle text-warning mr-4">
                            <i class="fa fa-refresh"></i>
                        </div>
                        <div class="media-body">
                            <h5>Free Return</h5>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



	    <section class="products-grids trending pb-4">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <div class="section-title">
                       
                    </div>
                </div>
            </div>

           

         


            <section class="sellerBanner">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="leftSiderbar">
                                <nav class="nav-category my-2">
                                    <h2>Brand</h2>
                                        
                                    <ul class="menu-category">
                                        {% for i in brand %}
                                        <li><a href="/?brand={{i.id}}">{{i.title}}</a></li>
                                        {% endfor %}   
                                    </ul>
                                </nav> 


                                <nav class="nav-category my-3">
                                    <h2>Storage</h2>
                                        
                                    <ul class="menu-category">
                                        {% for s in storage %}
                                        <li><a href="/?storage={{s.id}}">{{s.title}}</a></li>
                                        {% endfor %}   
                                    </ul>
                                </nav> 
                               
                                
                               
                               
                                
                               
                            </div>
                           

                        </div>

                        <div class="col-md-10">
                            <div class="row mt-4 ">     
                                {% for p in product %}
                                <div class="col-xl-3 col-lg-4 col-md-4 col-12  my-2">
                                    <div class="single-product">
                                        <div class="product-img">
                                            <a href="{% url 'product-detail' p.id %}">
                                                <img src="{{p.image.url}}" class="img-fluid" />
                                            </a>
                                        </div>
                                       
                                        <div class="product-content text-center">
                                            <h3 class=""><a href="{% url 'product-detail' p.id %}">{{p.title}}</a></h3>
                                            <div class="product-price">
                                                
                                                {% comment %} <span>Rs. {{p.selling_price }}</span> {% endcomment %}
                                                <P><strike> Rs. {{p.marked_price }}   </strike>   Rs. {{p.selling_price}}</P>
                                               
                                                <a href="{% url 'product-detail' p.id %}" class="btn btn-primary pull-center">Detail</a>
                                               
                                               
                                             
                                            
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                                    {% endfor %}
                            
                            </div>
                           


                            
                        </div>
                    </div>
                </div>

            </section>


    
            
<div class="pagination my-4">
        {% if product.has_previous %}
            <a href="?page=1"></a>
            <a href="?page={{product.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ product.number }} of {{ product.paginator.num_pages }}.
        </span>

        {% if product.has_next %}
            <a href="?page={{ product.next_page_number }}">Next </a>
            <a href="?page={{ product.paginator.num_pages }}"> &raquo;</a>
        {% endif %}
    </span>
</div>
       
        </div>
    </section>
    

{% endblock main-contents %}

app/templates/app/productdetail.html
{% extends 'app/bases.html' %}
{% load static %}
{% block title %}{{product.description}}{% endblock title %}

{% block main-contents %}


<section class="breadcrumb-section pb-3 pt-3">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Products</a></li>
                <li class="breadcrumb-item active" aria-current="page">Product Detail</li>
            </ol>
        </div>
    </section>
    <section class="product-page pb-4 pt-4">
        <div class="container">
            <div class="row product-detail-inner">
                <div class="col-lg-6 col-md-6 col-12">
                    <div id="product-images" class="carousel slide" data-ride="carousel">
                        <!-- slides -->
                        <div class="carousel-inner">
                            <div class="carousel-item active"> <img src="{{ product.image.url}}" class="img-fluid" alt="Product 1"> </div>

                            {% for p in  product.productimage_set.all %}
                            <div class="carousel-item">
                            
                             <img src="{{p.image.url}}" class="img-fluid" alt="Product 2"> 

                             </div>
                            {%endfor%}
                            
                        </div> <!-- Left right -->
                        <a class="carousel-control-prev" href="#product-images" data-slide="prev"> <span class="carousel-control-prev-icon"></span> </a> <a class="carousel-control-next" href="#product-images" data-slide="next"> <span class="carousel-control-next-icon"></span> </a><!-- Thumbnails -->
                        <ol class="carousel-indicators list-inline">
                            <li class="list-inline-item active"> <a id="carousel-selector-0" class="selected" data-slide-to="0" data-target="#product-images"> <img src="{{ product.image.url}}"  class="img-fluid"> </a> </li>
                            {% for p in  product.productimgae_set.all %}
                            <li class="list-inline-item"> <a id="carousel-selector-1" data-slide-to="1" data-target="#product-images"> <img src="{{p.image.url}}"  class="img-fluid"> </a> </li>
                           {%endfor%}
                       </ol>
                                                     
                    </div>
                </div>


                <div class="col-lg-6 col-md-6 col-12">
                    <div class="product-detail product_data">
                        
                        
                        <div class="product-short-desc">
                            <p>
							{{product.description}}
                            </p>
                            <hr>
                        <div class="product-price">
                            <span class="price"> Rs.  {{product.selling_price}}</span><span class="price-muted">Rs. {{ product.marked_price}}  </span>
                        </div>
                            
                        </div>
                        <div class="product-select">
                            <form>
                                <div class="form-group">
                                    <label>Warranty</label>
                                    <select class="form-control">
                                        <option>{{product.warranty}}</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Return policy</label>
                                    <select class="form-control">
                                        <option>{{product.return_policy}}</option>
                                    </select>
                                </div>
                               

                                 
                                <div class="row">
                                    {% if request.user.is_authenticated %}
                                   
                                     <div class="col-md-5">
                                        
                                        <a href="{% url 'addtocart' product.id %}" <button name='product' value='{{product.id}}' class="btn btn-primary btn-block update-cart" >Add to Cart</button> </a>
                                    </div> 

                                    {% else %}
                                     <div class="col-md-5">
                                        <a href="{% url 'customerlogin'%}" <button type="button"  class="btn btn-primary btn-block "  >Add to Cart</button> </a>
                                    </div> 

                                    
                                    {% endif %}

                                    {% if request.user.is_authenticated %}
                                    <button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
                                    {% else %}
                                    <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>

                                    {% endif %}

                                </div>
                            </form>
                        </div>
                        <div class="product-categories">
                            <ul>
                                <li class="categories-title">Views :</li>
                                <li><a href="#">({{product.view_count}} times)</a></li>
                               
                            </ul>
                        </div>
                        
                        <div class="product-share">
                            <ul>
                                <li class="categories-title">Share :</li>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                            </ul>
                        </div>
                   
                    </div>
                </div>
                <div class="container">
                     <div class="m-4">
                        <h2>About this Product</h2>
                           <p> {{product.full_description}}</p>   
                        </div>
                    </div>
               
            </div>
           
            </div>

            
 





        
                  
                                   
{% endblock main-contents %}